// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDY2Si7aRYEpTjkh125Tb6Wgj2q74q-tM',
    appId: '1:292809248232:web:5c798b97345102e172a85d',
    messagingSenderId: '292809248232',
    projectId: 'mali-not-app',
    authDomain: 'mali-not-app.firebaseapp.com',
    storageBucket: 'mali-not-app.firebasestorage.app',
    measurementId: 'G-DK2WVMDL6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXbKR-XSyQMvVjgHbcQMWCqf5F6hmnnKs',
    appId: '1:292809248232:android:3d8928d748540aa172a85d',
    messagingSenderId: '292809248232',
    projectId: 'mali-not-app',
    storageBucket: 'mali-not-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj5kkcgKmDG1edftybTWEco6qw8K7LbDI',
    appId: '1:292809248232:ios:3b1cc0339c4e935572a85d',
    messagingSenderId: '292809248232',
    projectId: 'mali-not-app',
    storageBucket: 'mali-not-app.firebasestorage.app',
    iosBundleId: 'com.noteapp.mynoteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj5kkcgKmDG1edftybTWEco6qw8K7LbDI',
    appId: '1:292809248232:ios:3b1cc0339c4e935572a85d',
    messagingSenderId: '292809248232',
    projectId: 'mali-not-app',
    storageBucket: 'mali-not-app.firebasestorage.app',
    iosBundleId: 'com.noteapp.mynoteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDY2Si7aRYEpTjkh125Tb6Wgj2q74q-tM',
    appId: '1:292809248232:web:13eb90184663a9d272a85d',
    messagingSenderId: '292809248232',
    projectId: 'mali-not-app',
    authDomain: 'mali-not-app.firebaseapp.com',
    storageBucket: 'mali-not-app.firebasestorage.app',
    measurementId: 'G-KNGTT3PSBQ',
  );
}
